<?php if (! $this->compact): ?>
	<div class="controls">
  		<?= $tabs; ?>
	</div>
<?php endif ?>

<?php if (! $this->compact): ?>
	<iframe id="nagvis-iframe" src="<?= $this->nagvisUrl ?>" width="100%" height="99%" marginheight=0 marginwidth=0 wspace=0 frameborder=0 ></iframe>
<?php else: ?>
	<iframe id="nagvis-iframe" src="<?= $this->nagvisUrl . '&zoom=' . $zoom_pc;?>" width="100%" height="<?=$iframe_height_px;?>" marginheight=0 marginwidth=0 wspace=0 frameborder=0 scrolling="no"</iframe>
<?php endif; ?>
